version: 'latest'

services:
  
  db:
    image: postgres

    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - './database:/var/lib/postgresql/data'
    

  
  web:
    depends_on:
      - db
    build: .

    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
  